export default [
  {
    id: Math.random().toString(),
    drugName: 'Ataxil',
    dose: '130mg',
    bsa: '196',
    doctor: 'Egemen Işık',
    hospital: 'Muğla Devlet Hastanesi',
    date: '18 Ağustos 2020',
  },
  {
    id: Math.random().toString(),
    drugName: 'Ataxil',
    dose: '130mg',
    bsa: '196',
    doctor: 'Egemen Işık',
    hospital: 'Muğla Devlet Hastanesi',
    date: '18 Ağustos 2020',
  },
  {
    id: Math.random().toString(),
    drugName: 'Ataxil',
    dose: '130mg',
    bsa: '196',
    doctor: 'Egemen Işık',
    hospital: 'Muğla Devlet Hastanesi',
    date: '18 Ağustos 2020',
  },
  {
    id: Math.random().toString(),
    drugName: 'Ataxil',
    dose: '130mg',
    bsa: '196',
    doctor: 'Egemen Işık',
    hospital: 'Muğla Devlet Hastanesi',
    date: '18 Ağustos 2020',
  },
  {
    id: Math.random().toString(),
    drugName: 'Ataxil',
    dose: '130mg',
    bsa: '196',
    doctor: 'Egemen Işık',
    hospital: 'Muğla Devlet Hastanesi',
    date: '18 Ağustos 2020',
  },
  {
    id: Math.random().toString(),
    drugName: 'Ataxil',
    dose: '130mg',
    bsa: '196',
    doctor: 'Egemen Işık',
    hospital: 'Muğla Devlet Hastanesi',
    date: '18 Ağustos 2020',
  },
  {
    id: Math.random().toString(),
    drugName: 'Ataxil',
    dose: '130mg',
    bsa: '196',
    doctor: 'Egemen Işık',
    hospital: 'Muğla Devlet Hastanesi',
    date: '18 Ağustos 2020',
  },
];
